/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 48/0.1.0; intrinsic ABI: v1; catalog SHA-256: c9a48eceec12809b152680890c366ca4f1db1c711d9d5c09a5f5e2f5bad56c3d.
// LLVM source: aab11ee0ea5ea9a1d462ad0bc1fae9d9bb643019.

//! Generated intrinsic target tests: `elect` intrinsics.

use super::super::*;

#[test]
fn elect_sync_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0367").unwrap();
    assert_eq!(target.id, "elect_sync");
    assert_eq!(target.abi_id, "i0367");
    assert_eq!(target.dialect_op, "nvvm.elect_sync");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 80);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(90)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(80),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(80),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(
        target.selections,
        &[
            GeneratedSelectionAlternative {
                source_record: "INT_ELECT_SYNC_I",
                asm: "elect.sync \t$dest|$pred, $mask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 80",
                    "Subtarget->getSmVersion() >= 90"
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
            GeneratedSelectionAlternative {
                source_record: "INT_ELECT_SYNC_R",
                asm: "elect.sync \t$dest|$pred, $mask;",
                predicates: &[
                    "Subtarget->getPTXVersion() >= 80",
                    "Subtarget->getSmVersion() >= 90"
                ],
                constraints: GeneratedSelectionConstraints {
                    address_space: None,
                    immediate_bindings: &[]
                }
            },
        ]
    );
    assert_eq!(
        target.llvm.unwrap().properties,
        &["IntrConvergent", "IntrInaccessibleMemOnly"] as &[&str]
    );
}
