/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 48/0.1.0; intrinsic ABI: v1; catalog SHA-256: c9a48eceec12809b152680890c366ca4f1db1c711d9d5c09a5f5e2f5bad56c3d.
// LLVM source: aab11ee0ea5ea9a1d462ad0bc1fae9d9bb643019.

//! Generated intrinsic target tests: `packed_atomic` intrinsics.

use super::super::*;

#[test]
fn packed_atomic_add_f16x2_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0014").unwrap();
    assert_eq!(target.id, "packed_atomic_add_f16x2");
    assert_eq!(target.abi_id, "i0014");
    assert_eq!(target.dialect_op, "nvvm.packed_atomic_add");
    assert_eq!(
        target.variant,
        GeneratedIntrinsicVariant::PackedAtomic {
            format: GeneratedPackedAtomicFormat::F16x2
        }
    );
    assert_eq!(target.requirement.minimum_ptx.encoded(), 62);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(70)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(62),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(70),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(62),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(75),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert!(target.llvm.is_none());
}

#[test]
fn packed_atomic_add_bf16x2_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0015").unwrap();
    assert_eq!(target.id, "packed_atomic_add_bf16x2");
    assert_eq!(target.abi_id, "i0015");
    assert_eq!(target.dialect_op, "nvvm.packed_atomic_add");
    assert_eq!(
        target.variant,
        GeneratedIntrinsicVariant::PackedAtomic {
            format: GeneratedPackedAtomicFormat::Bf16x2
        }
    );
    assert_eq!(target.requirement.minimum_ptx.encoded(), 78);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(90)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert!(target.llvm.is_none());
}
