/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 48/0.1.0; intrinsic ABI: v1; catalog SHA-256: c9a48eceec12809b152680890c366ca4f1db1c711d9d5c09a5f5e2f5bad56c3d.
// LLVM source: aab11ee0ea5ea9a1d462ad0bc1fae9d9bb643019.

//! Generated intrinsic target tests: `stmatrix` intrinsics.

use super::super::*;

#[test]
fn stmatrix_m8n8_x2_b16_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0301").unwrap();
    assert_eq!(target.id, "stmatrix_m8n8_x2_b16");
    assert_eq!(target.abi_id, "i0301");
    assert_eq!(target.dialect_op, "nvvm.stmatrix_m8n8_x2");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 78);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(90)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert_eq!(
        target.llvm.unwrap().properties,
        &[
            "IntrArgMemOnly",
            "IntrConvergent",
            "IntrNoCallback",
            "IntrWriteMem",
            "NoCapture<arg0>",
            "WriteOnly<arg0>"
        ] as &[&str]
    );
}

#[test]
fn stmatrix_m8n8_x2_trans_b16_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0302").unwrap();
    assert_eq!(target.id, "stmatrix_m8n8_x2_trans_b16");
    assert_eq!(target.abi_id, "i0302");
    assert_eq!(target.dialect_op, "nvvm.stmatrix_m8n8_x2_trans");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 78);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(90)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert_eq!(
        target.llvm.unwrap().properties,
        &[
            "IntrArgMemOnly",
            "IntrConvergent",
            "IntrNoCallback",
            "IntrWriteMem",
            "NoCapture<arg0>",
            "WriteOnly<arg0>"
        ] as &[&str]
    );
}

#[test]
fn stmatrix_m8n8_x4_b16_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0303").unwrap();
    assert_eq!(target.id, "stmatrix_m8n8_x4_b16");
    assert_eq!(target.abi_id, "i0303");
    assert_eq!(target.dialect_op, "nvvm.stmatrix_m8n8_x4");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 78);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(90)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert_eq!(
        target.llvm.unwrap().properties,
        &[
            "IntrArgMemOnly",
            "IntrConvergent",
            "IntrNoCallback",
            "IntrWriteMem",
            "NoCapture<arg0>",
            "WriteOnly<arg0>"
        ] as &[&str]
    );
}

#[test]
fn stmatrix_m8n8_x4_trans_b16_target_matches_the_catalog() {
    let target = generated_intrinsic_target_by_marker("v1:i0304").unwrap();
    assert_eq!(target.id, "stmatrix_m8n8_x4_trans_b16");
    assert_eq!(target.abi_id, "i0304");
    assert_eq!(target.dialect_op, "nvvm.stmatrix_m8n8_x4_trans");
    assert_eq!(target.variant, GeneratedIntrinsicVariant::Scalar);
    assert_eq!(target.requirement.minimum_ptx.encoded(), 78);
    assert_eq!(
        target.requirement.hardware,
        const { GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(90)]) }
    );
    assert_eq!(
        target.backend_requirements,
        const {
            &[
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LlvmNvptx,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
                GeneratedBackendRequirement {
                    backend: GeneratedIntrinsicBackend::LibNvvm,
                    requirement: GeneratedTargetRequirement {
                        minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                        hardware: GeneratedHardwareTarget::AnyOf(&[
                            GeneratedHardwareAlternative::MinimumSm(90),
                        ]),
                    },
                },
            ]
        }
    );
    assert_eq!(target.selections, &[]);
    assert_eq!(
        target.llvm.unwrap().properties,
        &[
            "IntrArgMemOnly",
            "IntrConvergent",
            "IntrNoCallback",
            "IntrWriteMem",
            "NoCapture<arg0>",
            "WriteOnly<arg0>"
        ] as &[&str]
    );
}
