/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: b0f689809eb546569bb1ab1210d84798d36f15339d440967024ed48bed9da095.
// LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

//! Generated conversion interfaces: `cache_policy` intrinsics.

use crate::conversion_interface::MirToLlvmConversion;
use crate::convert::intrinsics::cache_policy::convert_generated_cache_policy;
use dialect_nvvm::ops::{
    CreatepolicyFractionalEvictFirstEvictFirstOp, CreatepolicyFractionalEvictFirstOp,
    CreatepolicyFractionalEvictLastEvictFirstOp, CreatepolicyFractionalEvictLastOp,
    CreatepolicyFractionalEvictNormalEvictFirstOp, CreatepolicyFractionalEvictNormalOp,
    CreatepolicyFractionalEvictUnchangedEvictFirstOp, CreatepolicyFractionalEvictUnchangedOp,
};
use pliron::context::Context;
use pliron::derive::op_interface_impl;
use pliron::irbuild::dialect_conversion::{DialectConversionRewriter, OperandsInfo};
use pliron::op::Op;
use pliron::result::Result;

#[op_interface_impl]
impl MirToLlvmConversion for CreatepolicyFractionalEvictFirstOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_cache_policy(
            ctx,
            rewriter,
            self.get_operation(),
            "createpolicy.fractional.L2::evict_first.b64",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for CreatepolicyFractionalEvictFirstEvictFirstOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_cache_policy(
            ctx,
            rewriter,
            self.get_operation(),
            "createpolicy.fractional.L2::evict_first.L2::evict_first.b64",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for CreatepolicyFractionalEvictLastOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_cache_policy(
            ctx,
            rewriter,
            self.get_operation(),
            "createpolicy.fractional.L2::evict_last.b64",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for CreatepolicyFractionalEvictLastEvictFirstOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_cache_policy(
            ctx,
            rewriter,
            self.get_operation(),
            "createpolicy.fractional.L2::evict_last.L2::evict_first.b64",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for CreatepolicyFractionalEvictNormalOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_cache_policy(
            ctx,
            rewriter,
            self.get_operation(),
            "createpolicy.fractional.L2::evict_normal.b64",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for CreatepolicyFractionalEvictNormalEvictFirstOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_cache_policy(
            ctx,
            rewriter,
            self.get_operation(),
            "createpolicy.fractional.L2::evict_normal.L2::evict_first.b64",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for CreatepolicyFractionalEvictUnchangedOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_cache_policy(
            ctx,
            rewriter,
            self.get_operation(),
            "createpolicy.fractional.L2::evict_unchanged.b64",
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for CreatepolicyFractionalEvictUnchangedEvictFirstOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_cache_policy(
            ctx,
            rewriter,
            self.get_operation(),
            "createpolicy.fractional.L2::evict_unchanged.L2::evict_first.b64",
        )
    }
}
