/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 48/0.1.0; intrinsic ABI: v1; catalog SHA-256: c9a48eceec12809b152680890c366ca4f1db1c711d9d5c09a5f5e2f5bad56c3d.
// LLVM source: aab11ee0ea5ea9a1d462ad0bc1fae9d9bb643019.

//! Generated conversion interfaces: `dotprod` intrinsics.

use crate::conversion_interface::MirToLlvmConversion;
use crate::convert::intrinsics::dotprod::convert_generated_dot_product;
use dialect_nvvm::ops::{Dp2aS32Op, Dp2aU32Op, Dp4aS32Op, Dp4aU32Op};
use pliron::context::Context;
use pliron::derive::op_interface_impl;
use pliron::irbuild::dialect_conversion::{DialectConversionRewriter, OperandsInfo};
use pliron::op::Op;
use pliron::result::Result;

#[op_interface_impl]
impl MirToLlvmConversion for Dp2aS32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_dot_product(
            ctx,
            rewriter,
            self.get_operation(),
            "llvm_nvvm_idp2a_s_s",
            "dp2a.lo.s32.s32 $0, $1, $2, $3;",
            true,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for Dp2aU32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_dot_product(
            ctx,
            rewriter,
            self.get_operation(),
            "llvm_nvvm_idp2a_u_u",
            "dp2a.lo.u32.u32 $0, $1, $2, $3;",
            true,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for Dp4aS32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_dot_product(
            ctx,
            rewriter,
            self.get_operation(),
            "llvm_nvvm_idp4a_s_s",
            "dp4a.s32.s32 $0, $1, $2, $3;",
            false,
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for Dp4aU32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        convert_generated_dot_product(
            ctx,
            rewriter,
            self.get_operation(),
            "llvm_nvvm_idp4a_u_u",
            "dp4a.u32.u32 $0, $1, $2, $3;",
            false,
        )
    }
}
