/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: b0f689809eb546569bb1ab1210d84798d36f15339d440967024ed48bed9da095.
// LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

//! Generated conversion interfaces: `elect` intrinsics.

use crate::conversion_interface::MirToLlvmConversion;
use crate::convert::intrinsics::{warp::convert_elect_sync_inline, warp::convert_elect_sync_typed};
use crate::{IntrinsicBackend, context};
use dialect_nvvm::ops::ElectSyncOp;
use pliron::context::Context;
use pliron::derive::op_interface_impl;
use pliron::irbuild::dialect_conversion::{DialectConversionRewriter, OperandsInfo};
use pliron::op::Op;
use pliron::result::Result;

#[op_interface_impl]
impl MirToLlvmConversion for ElectSyncOp {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        match context::lowering_options(ctx).intrinsic_backend {
            IntrinsicBackend::LlvmNvptx => convert_elect_sync_typed(
                ctx,
                rewriter,
                self.get_operation(),
                operands_info,
                "llvm_nvvm_elect_sync",
            ),
            IntrinsicBackend::LibNvvm => {
                convert_elect_sync_inline(ctx, rewriter, self.get_operation(), operands_info)
            }
        }
    }
}
