/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 48/0.1.0; intrinsic ABI: v1; catalog SHA-256: c9a48eceec12809b152680890c366ca4f1db1c711d9d5c09a5f5e2f5bad56c3d.
// LLVM source: aab11ee0ea5ea9a1d462ad0bc1fae9d9bb643019.

//! Generated conversion interfaces: `movmatrix` intrinsics.

use crate::conversion_interface::MirToLlvmConversion;
use crate::convert::intrinsics::common::inline_asm_convergent;
use dialect_nvvm::ops::MovmatrixTransB16Op;
use pliron::builtin::types::{IntegerType, Signedness};
use pliron::context::Context;
use pliron::derive::op_interface_impl;
use pliron::irbuild::dialect_conversion::{DialectConversionRewriter, OperandsInfo};
use pliron::irbuild::rewriter::Rewriter;
use pliron::op::Op;
use pliron::result::Result;

#[op_interface_impl]
impl MirToLlvmConversion for MovmatrixTransB16Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        _operands_info: &OperandsInfo,
    ) -> Result<()> {
        let op = self.get_operation();
        let operands: Vec<_> = op.deref(ctx).operands().collect();
        if operands.len() != 1 {
            return pliron::input_err_noloc!(
                "movmatrix_trans_b16 requires 1 operand, got {}",
                operands.len()
            );
        }
        let result_ty = IntegerType::get(ctx, 32, Signedness::Signless);
        let asm = inline_asm_convergent(
            ctx,
            rewriter,
            op,
            result_ty.into(),
            operands,
            "movmatrix.sync.aligned.m8n8.trans.b16 $0, $1;",
            "=r,r",
        );
        rewriter.replace_operation(ctx, op, asm);
        Ok(())
    }
}
