/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 48/0.1.0; intrinsic ABI: v1; catalog SHA-256: c9a48eceec12809b152680890c366ca4f1db1c711d9d5c09a5f5e2f5bad56c3d.
// LLVM source: aab11ee0ea5ea9a1d462ad0bc1fae9d9bb643019.

//! Generated conversion interfaces: `warp_match` intrinsics.

use crate::conversion_interface::MirToLlvmConversion;
use crate::convert::intrinsics::{warp::convert_match_all, warp::convert_match_any};
use dialect_nvvm::ops::{
    MatchAllSyncI32Op, MatchAllSyncI64Op, MatchAnySyncI32Op, MatchAnySyncI64Op,
};
use pliron::builtin::types::{IntegerType, Signedness};
use pliron::context::Context;
use pliron::derive::op_interface_impl;
use pliron::irbuild::dialect_conversion::{DialectConversionRewriter, OperandsInfo};
use pliron::op::Op;
use pliron::result::Result;

#[op_interface_impl]
impl MirToLlvmConversion for MatchAllSyncI64Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        let value_ty = IntegerType::get(ctx, 64, Signedness::Signless);
        convert_match_all(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_match_all_sync_i64p",
            value_ty.into(),
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for MatchAllSyncI32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        let value_ty = IntegerType::get(ctx, 32, Signedness::Signless);
        convert_match_all(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_match_all_sync_i32p",
            value_ty.into(),
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for MatchAnySyncI64Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        let value_ty = IntegerType::get(ctx, 64, Signedness::Signless);
        convert_match_any(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_match_any_sync_i64",
            value_ty.into(),
        )
    }
}

#[op_interface_impl]
impl MirToLlvmConversion for MatchAnySyncI32Op {
    fn convert(
        &self,
        ctx: &mut Context,
        rewriter: &mut DialectConversionRewriter,
        operands_info: &OperandsInfo,
    ) -> Result<()> {
        let value_ty = IntegerType::get(ctx, 32, Signedness::Signless);
        convert_match_any(
            ctx,
            rewriter,
            self.get_operation(),
            operands_info,
            "llvm_nvvm_match_any_sync_i32",
            value_ty.into(),
        )
    }
}
