schema = 28
family = "prmt"

[prmt]

[[prmt.variant]]
abi_id = "i0252"
mode = "generic"

[[prmt.variant]]
abi_id = "i0253"
mode = "f4e"

[[prmt.variant]]
abi_id = "i0254"
mode = "b4e"

[[prmt.variant]]
abi_id = "i0255"
mode = "rc8"

[[prmt.variant]]
abi_id = "i0256"
mode = "ecl"

[[prmt.variant]]
abi_id = "i0257"
mode = "ecr"

[[prmt.variant]]
abi_id = "i0258"
mode = "rc16"
