schema = 35
family = "stmatrix"

[stmatrix]

[[stmatrix.variant]]
abi_id = "i0301"
multiplicity = "x2"
layout = "normal"

[[stmatrix.variant]]
abi_id = "i0302"
multiplicity = "x2"
layout = "transposed"

[[stmatrix.variant]]
abi_id = "i0303"
multiplicity = "x4"
layout = "normal"

[[stmatrix.variant]]
abi_id = "i0304"
multiplicity = "x4"
layout = "transposed"
