; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: f3df00d5a2a74df637ea3a641d05f161d6005c375388e55da24b7d908c39ecdc.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare void @llvm.nvvm.barrier.cta.arrive.count(i32, i32)

define void @probe_barrier_cta_arrive_rr(i32 %barrier_id, i32 %thread_count) #0 {
  call void @llvm.nvvm.barrier.cta.arrive.count(i32 %barrier_id, i32 %thread_count)
  ret void
}

define void @probe_barrier_cta_arrive_ri(i32 %barrier_id) #0 {
  call void @llvm.nvvm.barrier.cta.arrive.count(i32 %barrier_id, i32 32)
  ret void
}

define void @probe_barrier_cta_arrive_ir(i32 %thread_count) #0 {
  call void @llvm.nvvm.barrier.cta.arrive.count(i32 1, i32 %thread_count)
  ret void
}

define void @probe_barrier_cta_arrive_ii() #0 {
  call void @llvm.nvvm.barrier.cta.arrive.count(i32 1, i32 32)
  ret void
}

attributes #0 = { convergent }
