; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: f3df00d5a2a74df637ea3a641d05f161d6005c375388e55da24b7d908c39ecdc.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare void @llvm.nvvm.clusterlaunchcontrol.try_cancel.async.multicast.shared(ptr addrspace(3), ptr addrspace(3))

define void @probe_clc_try_cancel_multicast(ptr %response_generic, ptr %mbarrier_generic) {
  %response = addrspacecast ptr %response_generic to ptr addrspace(3)
  %mbarrier = addrspacecast ptr %mbarrier_generic to ptr addrspace(3)
  call void @llvm.nvvm.clusterlaunchcontrol.try_cancel.async.multicast.shared(ptr addrspace(3) %response, ptr addrspace(3) %mbarrier)
  ret void
}
