; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: e136187043d5f30ee64e3450e50bd3af60308b48723ec0fd65afc2cd29640e37.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare i32 @llvm.nvvm.read.ptx.sreg.cluster.nctarank()

define i32 @probe_cluster_block_count() {
  %result = call i32 @llvm.nvvm.read.ptx.sreg.cluster.nctarank()
  ret i32 %result
}

