; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: f3df00d5a2a74df637ea3a641d05f161d6005c375388e55da24b7d908c39ecdc.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare void @llvm.nvvm.cp.async.bulk.tensor.prefetch.tile.gather4.2d(ptr, i32, i32, i32, i32, i32, i64, i1) #0

define void @probe_cp_async_bulk_prefetch_tensor_gather4_2d_l2_cache_hint(ptr %tensor_map, i32 %coord0, i32 %coord1, i32 %coord2, i32 %coord3, i32 %coord4, i64 %cache_hint) #0 {
  call void @llvm.nvvm.cp.async.bulk.tensor.prefetch.tile.gather4.2d(ptr %tensor_map, i32 %coord0, i32 %coord1, i32 %coord2, i32 %coord3, i32 %coord4, i64 %cache_hint, i1 true) #0
  ret void
}

attributes #0 = { convergent }
