; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: e136187043d5f30ee64e3450e50bd3af60308b48723ec0fd65afc2cd29640e37.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare void @llvm.nvvm.cp.async.bulk.prefetch.L2(ptr addrspace(1), i32, i64, i1) #0

define void @probe_cp_async_bulk_prefetch_l2_cache_hint(ptr %src_generic, i32 %size, i64 %cache_hint) #0 {
  %src = addrspacecast ptr %src_generic to ptr addrspace(1)
  call void @llvm.nvvm.cp.async.bulk.prefetch.L2(ptr addrspace(1) %src, i32 %size, i64 %cache_hint, i1 true) #0
  ret void
}

attributes #0 = { convergent }
