; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: e136187043d5f30ee64e3450e50bd3af60308b48723ec0fd65afc2cd29640e37.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare void @llvm.nvvm.cp.async.bulk.shared.cta.to.global.bytemask(ptr addrspace(1), ptr addrspace(3), i32, i64, i1, i16) #0

define void @probe_cp_async_bulk_s2g_byte_mask_cache_hint(ptr %dst_generic, ptr %src_generic, i32 %size, i64 %cache_hint, i16 %byte_mask) #0 {
  %dst = addrspacecast ptr %dst_generic to ptr addrspace(1)
  %src = addrspacecast ptr %src_generic to ptr addrspace(3)
  call void @llvm.nvvm.cp.async.bulk.shared.cta.to.global.bytemask(ptr addrspace(1) %dst, ptr addrspace(3) %src, i32 %size, i64 %cache_hint, i1 true, i16 %byte_mask) #0
  ret void
}

attributes #0 = { convergent }
