; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: f3d74cc3c2ba8ee0d8c4678a2ec3bca8c5bdf3e3a7480181f3e3fd12015f6790.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare void @llvm.nvvm.cp.async.bulk.global.to.shared.cta(ptr addrspace(3), ptr addrspace(3), ptr addrspace(1), i32, i64, i1) #0

define void @probe_cp_async_bulk_g2s_cta_cache_hint(ptr %dst_generic, ptr %src_generic, i32 %size, ptr %barrier_generic, i64 %cache_hint) #0 {
  %dst = addrspacecast ptr %dst_generic to ptr addrspace(3)
  %barrier = addrspacecast ptr %barrier_generic to ptr addrspace(3)
  %src = addrspacecast ptr %src_generic to ptr addrspace(1)
  call void @llvm.nvvm.cp.async.bulk.global.to.shared.cta(ptr addrspace(3) %dst, ptr addrspace(3) %barrier, ptr addrspace(1) %src, i32 %size, i64 %cache_hint, i1 true) #0
  ret void
}

attributes #0 = { convergent }
