; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: b0f689809eb546569bb1ab1210d84798d36f15339d440967024ed48bed9da095.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare void @llvm.nvvm.cp.async.bulk.global.to.shared.cluster(ptr addrspace(7), ptr addrspace(3), ptr addrspace(1), i32, i16, i64, i1, i1) #0

define void @probe_cp_async_bulk_g2s_cache_hint(ptr %dst_generic, ptr %src_generic, i32 %size, ptr %barrier_generic, i64 %cache_hint) #0 {
  %dst = addrspacecast ptr %dst_generic to ptr addrspace(7)
  %barrier = addrspacecast ptr %barrier_generic to ptr addrspace(3)
  %src = addrspacecast ptr %src_generic to ptr addrspace(1)
  call void @llvm.nvvm.cp.async.bulk.global.to.shared.cluster(ptr addrspace(7) %dst, ptr addrspace(3) %barrier, ptr addrspace(1) %src, i32 %size, i16 0, i64 %cache_hint, i1 false, i1 true) #0
  ret void
}

attributes #0 = { convergent }
