; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: b0f689809eb546569bb1ab1210d84798d36f15339d440967024ed48bed9da095.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare void @llvm.nvvm.cp.async.ca.shared.global.16(ptr addrspace(3), ptr addrspace(1))

define void @probe_cp_async_ca_16(ptr %shared_generic, ptr %global_generic) {
  %shared = addrspacecast ptr %shared_generic to ptr addrspace(3)
  %global = addrspacecast ptr %global_generic to ptr addrspace(1)
  call void @llvm.nvvm.cp.async.ca.shared.global.16(ptr addrspace(3) %shared, ptr addrspace(1) %global)
  ret void
}
