; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: f3d74cc3c2ba8ee0d8c4678a2ec3bca8c5bdf3e3a7480181f3e3fd12015f6790.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare i16 @llvm.nvvm.ff.to.e5m2x2.rn.relu(float, float)

define i16 @probe_cvt_rn_satfinite_relu_e5m2x2_f32(float %low, float %high) {
  %result = call i16 @llvm.nvvm.ff.to.e5m2x2.rn.relu(float %high, float %low)
  ret i16 %result
}
