; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: f3d74cc3c2ba8ee0d8c4678a2ec3bca8c5bdf3e3a7480181f3e3fd12015f6790.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare void @llvm.nvvm.fence.proxy.tensormap_generic.acquire.sys(ptr, i32)

define void @probe_fence_proxy_tensormap_generic_acquire_system(ptr %tensor_map) {
  call void @llvm.nvvm.fence.proxy.tensormap_generic.acquire.sys(ptr %tensor_map, i32 128)
  ret void
}
