; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: f3d74cc3c2ba8ee0d8c4678a2ec3bca8c5bdf3e3a7480181f3e3fd12015f6790.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

define i32 @probe_fma_ftz_relu_f16x2(i32 %arg0, i32 %arg1, i32 %arg2) {
  %result = call i32 asm "fma.rn.ftz.relu.f16x2 $0, $1, $2, $3;", "=r,r,r,r"(i32 %arg0, i32 %arg1, i32 %arg2)
  ret i32 %result
}
