; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: f3df00d5a2a74df637ea3a641d05f161d6005c375388e55da24b7d908c39ecdc.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare { i32, i32, i32, i32 } @llvm.nvvm.ldmatrix.sync.aligned.m8n8.x4.trans.b16.p3(ptr addrspace(3))

define { i32, i32, i32, i32 } @probe_ldmatrix_m8n8_x4_trans_b16(ptr %generic) {
  %shared = addrspacecast ptr %generic to ptr addrspace(3)
  %result = call { i32, i32, i32, i32 } @llvm.nvvm.ldmatrix.sync.aligned.m8n8.x4.trans.b16.p3(ptr addrspace(3) %shared)
  ret { i32, i32, i32, i32 } %result
}

