; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: f3d74cc3c2ba8ee0d8c4678a2ec3bca8c5bdf3e3a7480181f3e3fd12015f6790.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare { i32, i1 } @llvm.nvvm.match.all.sync.i64p(i32, i64)

define { i32, i1 } @probe_match_all_i64_sync_rr(i32 %member_mask, i64 %value) {
  %result = call { i32, i1 } @llvm.nvvm.match.all.sync.i64p(i32 %member_mask, i64 %value)
  ret { i32, i1 } %result
}
define { i32, i1 } @probe_match_all_i64_sync_ri(i64 %value) {
  %result = call { i32, i1 } @llvm.nvvm.match.all.sync.i64p(i32 -1, i64 %value)
  ret { i32, i1 } %result
}
define { i32, i1 } @probe_match_all_i64_sync_ir(i32 %member_mask) {
  %result = call { i32, i1 } @llvm.nvvm.match.all.sync.i64p(i32 %member_mask, i64 7)
  ret { i32, i1 } %result
}
define { i32, i1 } @probe_match_all_i64_sync_ii() {
  %result = call { i32, i1 } @llvm.nvvm.match.all.sync.i64p(i32 -1, i64 7)
  ret { i32, i1 } %result
}
