; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: b0f689809eb546569bb1ab1210d84798d36f15339d440967024ed48bed9da095.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare i64 @llvm.nvvm.mbarrier.arrive.noComplete.shared(ptr addrspace(3), i32)

define i64 @probe_mbarrier_arrive_no_complete(ptr %barrier_generic, i32 %count) {
  %barrier = addrspacecast ptr %barrier_generic to ptr addrspace(3)
  %state = call i64 @llvm.nvvm.mbarrier.arrive.noComplete.shared(ptr addrspace(3) %barrier, i32 %count)
  ret i64 %state
}
