; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: f3d74cc3c2ba8ee0d8c4678a2ec3bca8c5bdf3e3a7480181f3e3fd12015f6790.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

define { double, double } @probe_mma_m8n8k4_f64(double %c0, double %c1, double %a0, double %b0) #0 {
  %result = call { double, double } asm sideeffect "mma.sync.aligned.m8n8k4.row.col.f64.f64.f64.f64 {$0, $1}, {$4}, {$5}, {$2, $3};", "=d,=d,d,d,d,d"(double %c0, double %c1, double %a0, double %b0) #0
  ret { double, double } %result
}

attributes #0 = { convergent }
