; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: f3df00d5a2a74df637ea3a641d05f161d6005c375388e55da24b7d908c39ecdc.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare i32 @llvm.nvvm.read.ptx.sreg.nsmid()

define i32 @probe_nsmid_lib_nvvm() {
  %result = call i32 @llvm.nvvm.read.ptx.sreg.nsmid()
  ret i32 %result
}
