; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: f3df00d5a2a74df637ea3a641d05f161d6005c375388e55da24b7d908c39ecdc.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare void @llvm.nvvm.bar.warp.sync(i32)

define void @probe_sync_mask(i32 %member_mask) {
  call void @llvm.nvvm.bar.warp.sync(i32 %member_mask)
  ret void
}
define void @probe_sync_mask_immediate() {
  call void @llvm.nvvm.bar.warp.sync(i32 -1)
  ret void
}
