; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: e136187043d5f30ee64e3450e50bd3af60308b48723ec0fd65afc2cd29640e37.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

; LLVM source: llvm.nvvm.tcgen05.st.32x32b.x2; route: inline PTX; source contract: LlvmCustomLoweringWithoutSelection
define void @probe_tcgen05_st_32x32b_x2_raw(i32 %tmem, i32 %d0, i32 %d1) #0 {
  call void asm sideeffect "tcgen05.st.sync.aligned.32x32b.x2.b32 [$0], {$1,$2};", "r,r,r,~{memory}"(i32 %tmem, i32 %d0, i32 %d1) #0
  ret void
}

attributes #0 = { convergent }
