; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: f3d74cc3c2ba8ee0d8c4678a2ec3bca8c5bdf3e3a7480181f3e3fd12015f6790.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

; LLVM source: llvm.nvvm.tcgen05.ld.red.32x32b.x4.f32; route: inline PTX; source contract: LlvmCustomLoweringWithoutSelection
define void @probe_tcgen05_ld_red_32x32b_x4_min_abs_f32(i32 %tmem) #0 {
  %result = call { float, float, float, float, float } asm sideeffect "tcgen05.ld.red.sync.aligned.32x32b.x4.min.abs.f32 {$0,$1,$2,$3}, $4, [$5];", "=f,=f,=f,=f,=f,r,~{memory}"(i32 %tmem) #0
  ret void
}

attributes #0 = { convergent }
