; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: b0f689809eb546569bb1ab1210d84798d36f15339d440967024ed48bed9da095.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

; LLVM source: llvm.nvvm.tcgen05.mma.shared; route: inline PTX; source contract: TablegenSelectionChangesPtx
define void @probe_tcgen05_mma_e2m3(i32 %d_tmem, i64 %a_desc, i64 %b_desc, i32 %idesc, i1 %enable_d) #0 {
  call void asm sideeffect "{ .reg .pred %enable_pred; setp.ne.s32 %enable_pred, $4, 0; tcgen05.mma.cta_group::1.kind::f8f6f4.collector::a::discard [$0], $1, $2, $3, %enable_pred; }", "r,l,l,r,r,~{memory}"(i32 %d_tmem, i64 %a_desc, i64 %b_desc, i32 %idesc, i1 %enable_d) #0
  ret void
}

attributes #0 = { convergent }
