; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: b0f689809eb546569bb1ab1210d84798d36f15339d440967024ed48bed9da095.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

; LLVM source: llvm.nvvm.tcgen05.cp.4x256b.cg2; route: inline PTX; source contract: ExactTablegenSelection
define void @probe_tcgen05_cp_4x256b_cg2(i32 %tmem, i64 %desc) #0 {
  call void asm sideeffect "tcgen05.cp.cta_group::2.4x256b [$0], $1;", "r,l,~{memory}"(i32 %tmem, i64 %desc) #0
  ret void
}

attributes #0 = { convergent }
