; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: f3df00d5a2a74df637ea3a641d05f161d6005c375388e55da24b7d908c39ecdc.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

; LLVM source: llvm.nvvm.tcgen05.relinq.alloc.permit.cg1; route: inline PTX; source contract: ExactTablegenSelection
define void @probe_tcgen05_relinquish_alloc_permit() #0 {
  call void asm sideeffect "tcgen05.relinquish_alloc_permit.cta_group::1.sync.aligned;", "~{memory}"() #0
  ret void
}

attributes #0 = { convergent }
