; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: b0f689809eb546569bb1ab1210d84798d36f15339d440967024ed48bed9da095.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

; LLVM source: llvm.nvvm.tcgen05.ld.32x32b.x2; route: inline PTX; source contract: LlvmCustomLoweringWithoutSelection
define void @probe_tcgen05_ld_32x32b_x2_raw(i32 %tmem) #0 {
  %result = call { i32, i32 } asm sideeffect "tcgen05.ld.sync.aligned.32x32b.x2.b32 {$0,$1}, [$2];", "=r,=r,r,~{memory}"(i32 %tmem) #0
  ret void
}

attributes #0 = { convergent }
