/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: f3d74cc3c2ba8ee0d8c4678a2ec3bca8c5bdf3e3a7480181f3e3fd12015f6790.
// LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

//! Generated intrinsic target records: `active_mask` intrinsics.

use super::{
    GeneratedBackendRequirement, GeneratedHardwareAlternative, GeneratedHardwareTarget,
    GeneratedIntrinsicBackend, GeneratedIntrinsicTarget, GeneratedIntrinsicVariant,
    GeneratedLlvmFacts, GeneratedPtxVersion, GeneratedSelectionAlternative,
    GeneratedSelectionConstraints, GeneratedTargetRequirement,
};

pub(super) const TARGETS: &[GeneratedIntrinsicTarget] = &[GeneratedIntrinsicTarget {
    marker: "v1:i0044",
    id: "active_mask",
    abi_id: "i0044",
    dialect_op: "nvvm.activemask",
    variant: GeneratedIntrinsicVariant::Scalar,
    requirement: GeneratedTargetRequirement {
        minimum_ptx: GeneratedPtxVersion::from_encoded(62),
        hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(30)]),
    },
    backend_requirements: &[
        GeneratedBackendRequirement {
            backend: GeneratedIntrinsicBackend::LlvmNvptx,
            requirement: GeneratedTargetRequirement {
                minimum_ptx: GeneratedPtxVersion::from_encoded(62),
                hardware: GeneratedHardwareTarget::AnyOf(&[
                    GeneratedHardwareAlternative::MinimumSm(30),
                ]),
            },
        },
        GeneratedBackendRequirement {
            backend: GeneratedIntrinsicBackend::LibNvvm,
            requirement: GeneratedTargetRequirement {
                minimum_ptx: GeneratedPtxVersion::from_encoded(62),
                hardware: GeneratedHardwareTarget::AnyOf(&[
                    GeneratedHardwareAlternative::MinimumSm(75),
                ]),
            },
        },
    ],
    selections: &[GeneratedSelectionAlternative {
        source_record: "ACTIVEMASK",
        asm: "activemask.b32 \t$dest;",
        predicates: &[
            "Subtarget->getSmVersion() >= 30",
            "Subtarget->getPTXVersion() >= 62",
        ],
        constraints: GeneratedSelectionConstraints {
            address_space: None,
            immediate_bindings: &[],
        },
    }],
    llvm: Some(GeneratedLlvmFacts {
        properties: &[
            "IntrConvergent",
            "IntrHasSideEffects",
            "IntrInaccessibleMemOnly",
            "IntrNoCallback",
        ],
        result_no_undef: false,
        result_range: None,
    }),
}];
