/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: b0f689809eb546569bb1ab1210d84798d36f15339d440967024ed48bed9da095.
// LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

//! Generated intrinsic target records: `cache_policy` intrinsics.

use super::{
    GeneratedBackendRequirement, GeneratedHardwareAlternative, GeneratedHardwareTarget,
    GeneratedIntrinsicBackend, GeneratedIntrinsicTarget, GeneratedIntrinsicVariant,
    GeneratedPtxVersion, GeneratedTargetRequirement,
};

pub(super) const TARGETS: &[GeneratedIntrinsicTarget] = &[
    GeneratedIntrinsicTarget {
        marker: "v1:i1039",
        id: "createpolicy_fractional_evict_last",
        abi_id: "i1039",
        dialect_op: "nvvm.createpolicy_fractional_evict_last",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(74),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(74),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(74),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[],
        llvm: None,
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i1040",
        id: "createpolicy_fractional_evict_normal",
        abi_id: "i1040",
        dialect_op: "nvvm.createpolicy_fractional_evict_normal",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(74),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(74),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(74),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[],
        llvm: None,
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i1041",
        id: "createpolicy_fractional_evict_first",
        abi_id: "i1041",
        dialect_op: "nvvm.createpolicy_fractional_evict_first",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(74),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(74),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(74),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[],
        llvm: None,
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i1042",
        id: "createpolicy_fractional_evict_unchanged",
        abi_id: "i1042",
        dialect_op: "nvvm.createpolicy_fractional_evict_unchanged",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(74),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(74),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(74),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[],
        llvm: None,
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i1043",
        id: "createpolicy_fractional_evict_last_evict_first",
        abi_id: "i1043",
        dialect_op: "nvvm.createpolicy_fractional_evict_last_evict_first",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(74),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(74),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(74),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[],
        llvm: None,
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i1044",
        id: "createpolicy_fractional_evict_normal_evict_first",
        abi_id: "i1044",
        dialect_op: "nvvm.createpolicy_fractional_evict_normal_evict_first",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(74),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(74),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(74),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[],
        llvm: None,
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i1045",
        id: "createpolicy_fractional_evict_first_evict_first",
        abi_id: "i1045",
        dialect_op: "nvvm.createpolicy_fractional_evict_first_evict_first",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(74),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(74),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(74),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[],
        llvm: None,
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i1046",
        id: "createpolicy_fractional_evict_unchanged_evict_first",
        abi_id: "i1046",
        dialect_op: "nvvm.createpolicy_fractional_evict_unchanged_evict_first",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(74),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(74),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(74),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[],
        llvm: None,
    },
];
