/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 48/0.1.0; intrinsic ABI: v1; catalog SHA-256: c9a48eceec12809b152680890c366ca4f1db1c711d9d5c09a5f5e2f5bad56c3d.
// LLVM source: aab11ee0ea5ea9a1d462ad0bc1fae9d9bb643019.

//! Generated intrinsic target records: `mbarrier_basic` intrinsics.

use super::{
    GeneratedBackendRequirement, GeneratedHardwareAlternative, GeneratedHardwareTarget,
    GeneratedIntrinsicBackend, GeneratedIntrinsicTarget, GeneratedIntrinsicVariant,
    GeneratedLlvmFacts, GeneratedPtxVersion, GeneratedSelectionAlternative,
    GeneratedSelectionConstraints, GeneratedTargetRequirement,
};

pub(super) const TARGETS: &[GeneratedIntrinsicTarget] = &[
    GeneratedIntrinsicTarget {
        marker: "v1:i0097",
        id: "mbarrier_init",
        abi_id: "i0097",
        dialect_op: "nvvm.mbarrier_init_shared",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "MBARRIER_INIT_SHARED",
            asm: "mbarrier.init.shared.b64 \t[$addr], $count;",
            predicates: &[
                "Subtarget->getSmVersion() >= 80",
                "Subtarget->getPTXVersion() >= 70",
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrConvergent", "IntrNoCallback"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0098",
        id: "mbarrier_arrive",
        abi_id: "i0098",
        dialect_op: "nvvm.mbarrier_arrive_shared",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "MBARRIER_ARRIVE_SHARED",
            asm: "mbarrier.arrive.shared.b64 \t$state, [$addr];",
            predicates: &[
                "Subtarget->getSmVersion() >= 80",
                "Subtarget->getPTXVersion() >= 70",
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrConvergent", "IntrNoCallback"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0099",
        id: "mbarrier_test_wait",
        abi_id: "i0099",
        dialect_op: "nvvm.mbarrier_test_wait_shared",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "MBARRIER_TEST_WAIT_SHARED",
            asm: "mbarrier.test_wait.shared.b64 \t$res, [$addr], $state;",
            predicates: &[
                "Subtarget->getSmVersion() >= 80",
                "Subtarget->getPTXVersion() >= 70",
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrConvergent", "IntrNoCallback"],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i0100",
        id: "mbarrier_inval",
        abi_id: "i0100",
        dialect_op: "nvvm.mbarrier_inval_shared",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "MBARRIER_INVAL_SHARED",
            asm: "mbarrier.inval.shared.b64 \t[$addr];",
            predicates: &[
                "Subtarget->getSmVersion() >= 80",
                "Subtarget->getPTXVersion() >= 70",
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &[
                "IntrArgMemOnly",
                "IntrConvergent",
                "IntrNoCallback",
                "IntrWriteMem",
                "NoCapture<arg0>",
                "WriteOnly<arg0>",
            ],
            result_no_undef: false,
            result_range: None,
        }),
    },
    GeneratedIntrinsicTarget {
        marker: "v1:i1017",
        id: "mbarrier_arrive_no_complete",
        abi_id: "i1017",
        dialect_op: "nvvm.mbarrier_arrive_no_complete_shared",
        variant: GeneratedIntrinsicVariant::Scalar,
        requirement: GeneratedTargetRequirement {
            minimum_ptx: GeneratedPtxVersion::from_encoded(70),
            hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(
                80,
            )]),
        },
        backend_requirements: &[
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LlvmNvptx,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
            GeneratedBackendRequirement {
                backend: GeneratedIntrinsicBackend::LibNvvm,
                requirement: GeneratedTargetRequirement {
                    minimum_ptx: GeneratedPtxVersion::from_encoded(70),
                    hardware: GeneratedHardwareTarget::AnyOf(&[
                        GeneratedHardwareAlternative::MinimumSm(80),
                    ]),
                },
            },
        ],
        selections: &[GeneratedSelectionAlternative {
            source_record: "MBARRIER_ARRIVE_NOCOMPLETE_SHARED",
            asm: "mbarrier.arrive.noComplete.shared.b64 \t$state, [$addr], $count;",
            predicates: &[
                "Subtarget->getSmVersion() >= 80",
                "Subtarget->getPTXVersion() >= 70",
            ],
            constraints: GeneratedSelectionConstraints {
                address_space: None,
                immediate_bindings: &[],
            },
        }],
        llvm: Some(GeneratedLlvmFacts {
            properties: &["IntrConvergent", "IntrNoCallback"],
            result_no_undef: false,
            result_range: None,
        }),
    },
];
