/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

// @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
// Catalog schema/version: 48/0.1.0; intrinsic ABI: v1; catalog SHA-256: c9a48eceec12809b152680890c366ca4f1db1c711d9d5c09a5f5e2f5bad56c3d.
// LLVM source: aab11ee0ea5ea9a1d462ad0bc1fae9d9bb643019.

//! Generated intrinsic target records: `movmatrix` intrinsics.

use super::{
    GeneratedBackendRequirement, GeneratedHardwareAlternative, GeneratedHardwareTarget,
    GeneratedIntrinsicBackend, GeneratedIntrinsicTarget, GeneratedIntrinsicVariant,
    GeneratedPtxVersion, GeneratedTargetRequirement,
};

pub(super) const TARGETS: &[GeneratedIntrinsicTarget] = &[GeneratedIntrinsicTarget {
    marker: "v1:i0305",
    id: "movmatrix_trans_b16",
    abi_id: "i0305",
    dialect_op: "nvvm.movmatrix_trans_b16",
    variant: GeneratedIntrinsicVariant::Scalar,
    requirement: GeneratedTargetRequirement {
        minimum_ptx: GeneratedPtxVersion::from_encoded(78),
        hardware: GeneratedHardwareTarget::AnyOf(&[GeneratedHardwareAlternative::MinimumSm(75)]),
    },
    backend_requirements: &[
        GeneratedBackendRequirement {
            backend: GeneratedIntrinsicBackend::LlvmNvptx,
            requirement: GeneratedTargetRequirement {
                minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                hardware: GeneratedHardwareTarget::AnyOf(&[
                    GeneratedHardwareAlternative::MinimumSm(75),
                ]),
            },
        },
        GeneratedBackendRequirement {
            backend: GeneratedIntrinsicBackend::LibNvvm,
            requirement: GeneratedTargetRequirement {
                minimum_ptx: GeneratedPtxVersion::from_encoded(78),
                hardware: GeneratedHardwareTarget::AnyOf(&[
                    GeneratedHardwareAlternative::MinimumSm(75),
                ]),
            },
        },
    ],
    selections: &[],
    llvm: None,
}];
